# Generated by Django 4.0.1 on 2022-01-18 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_msg_message_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 19, 1, 59, 48, 875317)),
        ),
    ]
